"""
schemas.py — Pydantic data models for ProtMind API
---------------------------------------------------
Think of these as "contracts" between the API and its callers.
Every request/response body is validated automatically by FastAPI
before any of your code runs, so bad inputs never reach the model.
"""

from __future__ import annotations
from typing import List, Optional
from pydantic import BaseModel, Field, field_validator
import re


# ─────────────────────────────────────────────
# REQUEST MODELS
# ─────────────────────────────────────────────

class PredictRequest(BaseModel):
    """
    Body sent by the client for /predict and /explain endpoints.

    Example JSON:
        {"sequence": "MKTLLILAAVLFATSANA", "top_k": 10, "threshold": 0.5}
    """
    sequence: str = Field(
        ...,                                      # '...' means required
        description="Amino acid sequence in single-letter code (e.g. MKTLL...)",
        min_length=5,
        max_length=1024,                          # ESM2-150M safe upper bound
    )
    top_k: int = Field(
        default=10,
        ge=1,
        le=50,
        description="Return at most this many GO predictions",
    )
    threshold: float = Field(
        default=0.3,
        ge=0.0,
        le=1.0,
        description="Minimum sigmoid probability to consider a GO term active",
    )

    # ── Validator: strip whitespace and force uppercase ──────────────────
    @field_validator("sequence")
    @classmethod
    def clean_sequence(cls, v: str) -> str:
        v = v.strip().upper().replace(" ", "").replace("\n", "")
        # Standard 20 amino acids + common ambiguity codes
        allowed = set("ACDEFGHIKLMNPQRSTVWYBZXU")
        illegal = set(v) - allowed
        if illegal:
            raise ValueError(
                f"Sequence contains invalid characters: {illegal}. "
                "Only standard amino acid single-letter codes are accepted."
            )
        return v


# ─────────────────────────────────────────────
# RESPONSE MODELS
# ─────────────────────────────────────────────

class GOPrediction(BaseModel):
    """A single GO Molecular Function prediction."""
    go_id: str            = Field(..., description="GO term ID, e.g. GO:0003677")
    go_name: str          = Field(..., description="Human-readable GO term name")
    confidence: float     = Field(..., description="Sigmoid probability [0, 1]")
    rank: int             = Field(..., description="Rank among returned predictions (1 = highest confidence)")


class AttentionData(BaseModel):
    """Per-residue attention scores for heatmap rendering."""
    residue_attention: List[float] = Field(
        ...,
        description="List of floats, one per residue, representing its relative importance. "
                    "Values are min-max normalised to [0, 1]."
    )
    sequence_length: int = Field(..., description="Number of residues in the input sequence")


class PredictResponse(BaseModel):
    """Full response from /predict."""
    sequence_length: int
    predictions:     List[GOPrediction]
    attention:       AttentionData
    processing_time_ms: float = Field(..., description="Server-side inference time in milliseconds")


class ExplainResponse(BaseModel):
    """Full response from /explain — includes everything plus the LLM explanation."""
    sequence_length: int
    predictions:     List[GOPrediction]
    attention:       AttentionData
    llm_explanation: str = Field(
        ...,
        description="Plain-language biological explanation generated by the local LLM"
    )
    processing_time_ms: float


class HealthResponse(BaseModel):
    """Response from GET /health."""
    status:      str   = "ok"
    model_ready: bool
    device:      str   = Field(..., description="'cuda' or 'cpu'")
    ollama_ready: bool
    version:     str   = "1.0.0"